sonar.projectKey=lumitrace-ingest
sonar.projectName=Lumitrace Ingest API
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=dist/**,coverage/**,node_modules/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
